swagger: '2.0'
info:
  version: '1.0'
  title: Way-Farer-App
  description: Way-Farer is a public bus transportation booking App.
  contact: {}
host: my-way-farer-app.herokuapp.com
basePath: /api/v1
securityDefinitions: {}
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /auth/signin:
    post:
      description: This creates a new user account, and returns user_id, is_admin and jwt token.
      summary: https://my-way-farer-app.herokuapp.com/api/v1/auth/signup
      tags:
      - User
      operationId: AuthSigninPost
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/https%3A~1~1my-way-farer-app.herokuapp.com~1api~1v1~1auth~1signup-request'
      responses:
        200:
          description: ''
          headers: {}
  /users:
    get:
      description: This route requires an admin users token, which displays a users in a json format.
      summary: https://my-way-farer-app.herokuapp.com/api/v1/users
      tags:
      - User
      operationId: UsersGet
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          headers: {}
  /bookings:
    post:
      description: This route requires a token, which creates a new booking and returns the booking details as a json format.
      summary: https://my-way-farer-app.herokuapp.com/api/v1/bookings
      tags:
      - Booking
      operationId: BookingsPost
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/https%3A~1~1my-way-farer-app.herokuapp.com~1api~1v1~1bookings-request'
      responses:
        200:
          description: ''
          headers: {}
    get:
      description: >-
        This route requires a token.

        For an Admin user, this route displays all bookings.

        For a non-admin user, this route will display only the users bookings.
      summary: https://my-way-farer-app.herokuapp.com/api/v1/bookings
      tags:
      - Booking
      operationId: BookingsGet
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /bookings/1:
    delete:
      description: This route requires a token, which deletes the booking, and returns a message in json format.
      summary: https://my-way-farer-app.herokuapp.com/api/v1/bookings/1
      tags:
      - Booking
      operationId: Bookings1Delete
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /bookings/2:
    put:
      description: 'This route requires an admin users token, and changes the seat number for a user. '
      summary: https://my-way-farer-app.herokuapp.com/api/v1/bookings/2
      tags:
      - Booking
      operationId: Bookings2Put
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/https%3A~1~1my-way-farer-app.herokuapp.com~1api~1v1~1bookings~12-request'
      responses:
        200:
          description: ''
          headers: {}
  /bus:
    post:
      description: >
        This route requires an admin users token and creates a new bus.
      summary: https://my-way-farer-app.herokuapp.com/api/v1/buses
      tags:
      - Bus
      operationId: BusPost
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/https%3A~1~1my-way-farer-app.herokuapp.com~1api~1v1~1buses-request'
      responses:
        200:
          description: ''
          headers: {}
    get:
      description: This route requires an admin users token, which enables you to get all buses created
      summary: https://my-way-farer-app.herokuapp.com/api/v1/bus
      tags:
      - Bus
      operationId: BusGet
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /trips:
    post:
      description: This route requires an admin users token to create a new trip.
      summary: https://my-way-farer-app.herokuapp.com/api/v1/trips
      tags:
      - Trip
      operationId: TripsPost
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/https%3A~1~1my-way-farer-app.herokuapp.com~1api~1v1~1trips-request'
      responses:
        200:
          description: ''
          headers: {}
    get:
      description: This route requires a token to displays all trips
      summary: https://my-way-farer-app.herokuapp.com/api/v1/trips
      tags:
      - Trip
      operationId: TripsGet
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /trips/2:
    put:
      description: This route requires a token to cancel a trip.
      summary: https://my-way-farer-app.herokuapp.com/api/v1/trips/2
      tags:
      - Trip
      operationId: Trips2Put
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
definitions:
  https://my-way-farer-app.herokuapp.com/api/v1/auth/signup-request:
    title: https://my-way-farer-app.herokuapp.com/api/v1/auth/signup-request
    example:
      first_name: Ikechukwu
      last_name: Okoro
      email: ikeshegs@test.com
      password: C00ljoe.
    type: object
    properties:
      first_name:
        type: string
      last_name:
        type: string
      email:
        type: string
      password:
        type: string
    required:
    - first_name
    - last_name
    - email
    - password
  https://my-way-farer-app.herokuapp.com/api/v1/auth/signin-request:
    title: https://my-way-farer-app.herokuapp.com/api/v1/auth/signin-request
    example:
      email: ikeshegs@test.com
      password: C00ljoe.
    type: object
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
  https://my-way-farer-app.herokuapp.com/api/v1/bookings-request:
    title: https://my-way-farer-app.herokuapp.com/api/v1/bookings-request
    example:
      trip_id: 4
    type: object
    properties:
      trip_id:
        type: integer
        format: int32
    required:
    - trip_id
  https://my-way-farer-app.herokuapp.com/api/v1/bookings/2-request:
    title: https://my-way-farer-app.herokuapp.com/api/v1/bookings/2-request
    example:
      seat_number: 31
    type: object
    properties:
      seat_number:
        type: integer
        format: int32
    required:
    - seat_number
  https://my-way-farer-app.herokuapp.com/api/v1/buses-request:
    title: https://my-way-farer-app.herokuapp.com/api/v1/buses-request
    example:
      number_plate: ABC01fg
      manufacturer: Mercedes Benz
      model: Sprinter
      year: 2015
      capacity: 25
    type: object
    properties:
      number_plate:
        type: string
      manufacturer:
        type: string
      model:
        type: string
      year:
        type: integer
        format: int32
      capacity:
        type: integer
        format: int32
    required:
    - number_plate
    - manufacturer
    - model
    - year
    - capacity
  https://my-way-farer-app.herokuapp.com/api/v1/trips-request:
    title: https://my-way-farer-app.herokuapp.com/api/v1/trips-request
    example:
      bus_id: 2
      origin: Aba
      destination: Port Harcourt
      trip_date: 2019-08-31
      fare: 700
    type: object
    properties:
      bus_id:
        type: integer
        format: int32
      origin:
        type: string
      destination:
        type: string
      trip_date:
        type: string
      fare:
        type: integer
        format: int32
    required:
    - bus_id
    - origin
    - destination
    - trip_date
    - fare
tags:
- name: User
  description: User Routes
- name: Booking
  description: All Bookings Route.
- name: Bus
  description: All Bus Routes
- name: Trip
  description: ALl Trips Routes.
